#!/usr/bin/env bash

set -euo pipefail

TEMPTREE=pre-commit.$$

cleanup() {
    rm -rf "$TEMPTREE"
}

trap cleanup EXIT

git checkout-index -a --prefix="./$TEMPTREE/"

(cd "./$TEMPTREE" && make lint)
